name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install build dependencies
      run: |
        sudo apt-get update -q
        sudo apt-get install --no-install-recommends -qy texlive lmodern texlive-pictures
    - name: Build the PDF document
      run: |
        make clean
        make
    - name: Verify build
      run: make test
